name: Build and publish wheels

on:
  push:
    tags:
      - "v*"  # Trigger on version tags like v0.8.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12, macos-14]  # Intel + ARM Macs

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          # Build for Python 3.9-3.13 (modern versions only)
          CIBW_BUILD: cp39-* cp310-* cp311-* cp312-* cp313-*
          
          # Skip 32-bit builds and PyPy
          CIBW_SKIP: "*-win32 *-manylinux_i686 pp*"
          
          # Linux: use manylinux for compatibility
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
          
          # Install build dependencies
          CIBW_BEFORE_BUILD: pip install numpy pybind11
          
          # Test the built wheels
          CIBW_TEST_REQUIRES: numpy
          CIBW_TEST_COMMAND: python -c "import qhnswlib; print('✓ qhnswlib imported successfully')"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}